### ISSUE TITLE
Tomighty icon does not correctly show when the dark menubar is enabled

### ISSUE THREAD

**Issue by timgws** [tomighty/tomighty-osx#21] opened 2015-11-17 23:00 UTC
![screen shot 2015-11-18 at 9 58 49 am](https://cloud.githubusercontent.com/assets/1050232/11227600/fcd782e0-8dda-11e5-99ea-10e4f570ff23.png)

At first I was trying to work out why Tomighty wasn't doing anything, before I realised that the icon on the menu bar simply doesn't show anything!

![screen shot 2015-11-18 at 10 00 17 am](https://cloud.githubusercontent.com/assets/1050232/11227631/304a73ee-8ddb-11e5-8126-0d898ac94173.png)

**Comment by pelizza** [comment] 2016-01-14 15:26
Oh yeah, now I can find the icon! :D

**Comment by timgws** [comment] 2016-01-15 02:14
Here is some info on how to update the code to work correctly: http://stackoverflow.com/a/24644754/2143004

**Comment by winkelsdorf** [comment] 2016-01-19 21:26
Duplicate of #14, PR #16 waiting for merge.

**Comment by saerdnaer** [comment] 2016-02-04 16:43
Is there an unofficial binary release which includes this PR?

**Comment by kerstin** [comment] 2016-04-05 11:12
See also https://github.com/tomighty/tomighty/issues/106 for a workaround.

**Comment by dvntucker** [comment] 2016-09-04 21:03
This has been fixed in https://github.com/tomighty/tomighty-osx/pull/22

Fix will be in Tomighty 1.1

**Closed** 2016-09-04 21:28 UTC
Labels: enhancement
